import { supabase } from '../lib/supabase';
import type { TemplateLayoutSchema } from '../schema/TemplateSchema';

/**
 * TEMPLATE RECORD SCHEMA MATCHING SUPABASE DATABASE EXACTLY
 * Strict TypeScript (Zero Any)
 */
export interface TemplateRecord {
  id: string; // Supabase Auto-Generated UUID
  name: string;
  slug: string;
  description?: string;
  thumbnail?: string;
  preview?: string;
  layout_json: TemplateLayoutSchema;
  metadata?: Record<string, unknown>;
  version: string;
  status: string;
  published?: boolean;
  created_by?: string;
  created_at?: string;
  updated_at?: string;
  deleted_at?: string;
}

const TABLE_NAME = 'templates';

/**
 * REPOSITORY PATTERN: TEMPLATE REPOSITORY
 * Sole database interface. Supabase Database is the Single Source of Truth.
 * No client-side tpl-xxxx ID generation, no local storage fallback.
 */
export class TemplateRepository {
  /**
   * Fetch all template records from Supabase Database
   */
  static async getTemplates(onlyPublished: boolean = false): Promise<TemplateRecord[]> {
    console.log(`[TemplateRepository] SELECT REQUEST, onlyPublished: ${onlyPublished}`);
    try {
      let query = supabase
        .from(TABLE_NAME)
        .select('*')
        .is('deleted_at', null)
        .order('created_at', { ascending: false });

      if (onlyPublished) {
        query = query.eq('published', true);
      }

      const { data, error } = await query;

      if (error) {
        console.error('[TemplateRepository] SELECT ERROR:', error);
        throw error;
      }

      console.log('[TemplateRepository] SELECT RESPONSE count:', data?.length || 0, data);
      return (data || []).map((item) => ({
        ...item,
        layout_json: typeof item.layout_json === 'string' ? JSON.parse(item.layout_json) : item.layout_json,
      })) as TemplateRecord[];
    } catch (err) {
      console.error('[TemplateRepository] SELECT EXCEPTION:', err);
      return [];
    }
  }

  /**
   * Load a template record by UUID from Supabase Database
   */
  static async loadTemplate(id: string): Promise<TemplateRecord | null> {
    console.log(`[TemplateRepository] SELECT REQUEST for ID: "${id}"`);
    try {
      const { data, error } = await supabase
        .from(TABLE_NAME)
        .select('*')
        .eq('id', id)
        .is('deleted_at', null)
        .single();

      if (error) {
        console.error('[TemplateRepository] SELECT ERROR:', error);
        return null;
      }

      console.log('[TemplateRepository] SELECT RESPONSE:', data);
      return {
        ...data,
        layout_json: typeof data.layout_json === 'string' ? JSON.parse(data.layout_json) : data.layout_json,
      } as TemplateRecord;
    } catch (err) {
      console.error('[TemplateRepository] SELECT EXCEPTION:', err);
      return null;
    }
  }

  /**
   * CREATE TEMPLATE (SUPABASE INSERT - UUID AUTO-GENERATED BY DATABASE)
   */
  static async createTemplate(payload: Partial<TemplateRecord>): Promise<TemplateRecord> {
    const templateName = payload.name || 'Mẫu Thiệp Mới';
    const templateSlug = payload.slug || `template-${Date.now()}`;

    const defaultLayout: TemplateLayoutSchema = {
      id: 'draft',
      name: templateName,
      version: '1.0.0',
      pages: [
        {
          id: 'page-1',
          name: 'Trang 1',
          components: [], // Empty canvas ready for design!
        },
      ],
    };

    const insertData = {
      name: templateName,
      slug: templateSlug,
      description: payload.description || 'Mẫu thiệp cưới thiết kế tinh tế sang trọng.',
      thumbnail: payload.thumbnail || 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=600',
      preview: payload.preview || '',
      layout_json: payload.layout_json && payload.layout_json.pages ? payload.layout_json : defaultLayout,
      metadata: payload.metadata || {},
      version: payload.version || '1.0.0',
      status: payload.status || 'draft',
      published: payload.published ?? false,
    };

    console.log('[TemplateRepository] CREATE REQUEST (INSERT INTO templates):', insertData);

    const { data, error } = await supabase
      .from(TABLE_NAME)
      .insert(insertData)
      .select()
      .single();

    if (error) {
      console.error('[TemplateRepository] CREATE ERROR:', error);
      throw error;
    }

    // Assign created UUID to layout_json.id
    const createdRecord: TemplateRecord = {
      ...data,
      layout_json: {
        ...(typeof data.layout_json === 'string' ? JSON.parse(data.layout_json) : data.layout_json),
        id: data.id,
      },
    };

    console.log('[TemplateRepository] CREATE RESPONSE (UUID Generated by Supabase):', createdRecord);
    return createdRecord;
  }

  /**
   * UPDATE TEMPLATE (SUPABASE UPDATE WHERE id = ?)
   */
  static async updateTemplate(id: string, updates: Partial<TemplateRecord>): Promise<TemplateRecord> {
    console.log(`[TemplateRepository] UPDATE REQUEST for ID: "${id}":`, updates);

    const updatePayload: Record<string, unknown> = {
      updated_at: new Date().toISOString(),
    };

    if (updates.name !== undefined) updatePayload.name = updates.name;
    if (updates.slug !== undefined) updatePayload.slug = updates.slug;
    if (updates.description !== undefined) updatePayload.description = updates.description;
    if (updates.thumbnail !== undefined) updatePayload.thumbnail = updates.thumbnail;
    if (updates.preview !== undefined) updatePayload.preview = updates.preview;
    if (updates.layout_json !== undefined) updatePayload.layout_json = updates.layout_json;
    if (updates.metadata !== undefined) updatePayload.metadata = updates.metadata;
    if (updates.version !== undefined) updatePayload.version = updates.version;
    if (updates.status !== undefined) updatePayload.status = updates.status;
    if (updates.published !== undefined) updatePayload.published = updates.published;

    const { data, error } = await supabase
      .from(TABLE_NAME)
      .update(updatePayload)
      .eq('id', id)
      .select()
      .single();

    if (error) {
      console.error('[TemplateRepository] UPDATE ERROR:', error);
      throw error;
    }

    const updatedRecord: TemplateRecord = {
      ...data,
      layout_json: typeof data.layout_json === 'string' ? JSON.parse(data.layout_json) : data.layout_json,
    };

    console.log('[TemplateRepository] UPDATE RESPONSE:', updatedRecord);
    return updatedRecord;
  }

  /**
   * SAVE TEMPLATE (ALWAYS UPDATE EXISTING RECORD VIA ID)
   */
  static async saveTemplate(record: TemplateRecord): Promise<TemplateRecord> {
    console.log(`[TemplateRepository] SAVE REQUEST for ID: "${record.id}" -> Executing updateTemplate()`);
    return this.updateTemplate(record.id, record);
  }

  /**
   * DELETE TEMPLATE (SUPABASE DELETE WHERE id = ?)
   */
  static async deleteTemplate(id: string): Promise<boolean> {
    console.log(`[TemplateRepository] DELETE REQUEST for ID: "${id}"`);

    const { error } = await supabase
      .from(TABLE_NAME)
      .delete()
      .eq('id', id);

    if (error) {
      console.error('[TemplateRepository] DELETE ERROR:', error);
      throw error;
    }

    console.log(`[TemplateRepository] DELETE RESPONSE: Success for ID: "${id}"`);
    return true;
  }

  /**
   * DUPLICATE TEMPLATE
   */
  static async duplicateTemplate(sourceId: string): Promise<TemplateRecord | null> {
    console.log(`[TemplateRepository] DUPLICATE REQUEST for Source ID: "${sourceId}"`);
    const source = await this.loadTemplate(sourceId);
    if (!source) return null;

    const duplicatedData: Partial<TemplateRecord> = {
      name: `${source.name} (Bản Sao)`,
      slug: `${source.slug}-copy-${Date.now()}`,
      description: source.description,
      thumbnail: source.thumbnail,
      preview: source.preview,
      layout_json: JSON.parse(JSON.stringify(source.layout_json)),
      metadata: source.metadata || {},
      version: '1.0.0',
      status: 'draft',
      published: false,
    };

    return this.createTemplate(duplicatedData);
  }
}
